using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UiC.NetworkServer.Managers;
using UiC.ORM;
using UiC.ORM.SubSonic.SQLGeneration.Schema;

namespace UiC.NetworkServer.Records
{
    public class PlayerBannedRelator
    {
        public static string FetchQuery = "SELECT * FROM players_banned";
        public static string FetchQueryById = "SELECT * FROM players_banned WHERE PlayerId = @0";

    }

    [TableName("players_banned")]
    public partial class PlayerBannedRecord : IAutoGeneratedRecord
    {
        public PlayerBannedRecord()
        {

        }

        [PrimaryKey("Id", true)]
        public int Id
        {
            get;
            set;
        }

        private PlayerRecord m_player;

        [Ignore]
        public PlayerRecord Player
        {
            get
            {
                if (m_player == null)
                    m_player = PlayerManager.Instance.FindPlayerRecordById(PlayerId);

                return m_player;
            }
            set
            {
                m_player = value;
            }
        }

        [JsonIgnore]
        public int PlayerId
        {
            get;
            set;
        }

        public string Reason
        {
            get;
            set;
        }

        public string Server
        {
            get;
            set;
        }

        public string Reporter
        {
            get;
            set;
        }

        public DateTime RowAdded
        {
            get;
            set;
        }


    }
}
