using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UiC.ORM;
using UiC.ORM.SubSonic.SQLGeneration.Schema;

namespace UiC.NetworkServer.Records
{
    public class ServerRelator
    {
        public static string FetchQuery = "SELECT * FROM servers";
        public static string FetchQueryById = "SELECT * FROM servers WHERE Id = @0";

        public static string FetchQueryByHostnameAndIp = "SELECT * FROM servers WHERE Name = @0 AND IP = @1";

    }

    [TableName("servers")]
    public partial class ServerRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id", true)]
        public int Id
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }

        public string IP
        {
            get;
            set;
        }

        public bool IsOnline
        {
            get;
            set;
        }

        public DateTime RowAdded
        {
            get;
            set;
        }

        public DateTime RowUpdated
        {
            get;
            set;
        }
    }
}
